# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugs_configuration', '0004_auto_20170824_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='configuration',
            options={'ordering': ('pk',), 'verbose_name': 'configuration', 'verbose_name_plural': 'configurations'},
        ),
    ]
